services:
  # Development PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: exam_scheduler_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: exam_scheduler_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - exam_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Redis
  redis:
    image: redis:7-alpine
    container_name: exam_scheduler_redis_dev
    restart: unless-stopped
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    volumes:
      - redis_dev_data:/data
    networks:
      - exam_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prisma Studio for database management
  prisma-studio:
    image: node:18-alpine
    container_name: exam_scheduler_prisma_studio
    working_dir: /app
    command: sh -c "npm install -g prisma && prisma studio --hostname 0.0.0.0 --port 5555"
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/exam_scheduler_dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exam_dev_network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  exam_dev_network:
    driver: bridge
